### ISSUE TITLE
[PC,태블릿,모바일 공통]프로필사진 아래 직급, 타이틀 사이 영역 간격 조절

### ISSUE THREAD

**Issue by Ryuhwangbyeol** [SCV-Soft/SCV-Soft.github.io#19]
*PC, 태블릿, 모바일 공통으로 진행해주세요.

<img width="948" alt="2018-10-07 5 04 30" src="https://user-images.githubusercontent.com/13708611/46579773-25cba700-ca53-11e8-8ea8-12c36497fbbc.png">

**Comment by benjioh5** [comment]
이슈 해결 완료 하였으나, 이렇게 하는게 맞는지 확신이 없음 (실제 나온 결과는 너무 벌어져 있지 않나 싶음)

**Comment by KarryLenka** [comment]
<img width="808" alt="2018-10-12 5 37 43" src="https://user-images.githubusercontent.com/20009097/46858349-15963c00-ce46-11e8-86fe-9ab7106a8901.png">


간격이 너무 넓은 것 같습니다. 위 이미지 참고하시어 수정 부탁드립니다.

**Comment by benjioh5** [comment]
일단 이슈 대응 완료. 다시 한 번 말하지만 시안/요청사항/그리고 실 적용이 다 각각 다르게 나왔으므로 자세히 확인 부탁드립니다. xd 기반으로 1.5px로 나와서 반올림해서 2px로 계산했습니다

**Comment by KarryLenka** [comment]
오 결과물 이쁘게 나왔어요...! 이슈 클로징 하겠습니다!
