### ISSUE TITLE
[PC,태블릿,모바일 공통] project section overflow 처리

### ISSUE THREAD

**Issue by astean1001** [SCV-Soft/SCV-Soft.github.io#27]
project section의 overflow로 인해서 footer가 일부 겹쳐지게 됩니다.
이 부분 처리 바랍니다.

Recommend Solution (Not Clean) : 
#project { overflow-y hidden }

**Comment by benjioh5** [comment]
확인 중

**Comment by benjioh5** [comment]
해결
