### ISSUE TITLE
AOS 팝업 애니메이션 추가

### ISSUE THREAD

**Issue by astean1001** [SCV-Soft/SCV-Soft.github.io#28]
적용하면 좋을것 같아요. 팀장님 적용 범위 설정해 주세요...!
[참조링크](https://michalsnik.github.io/aos/)

**Comment by benjioh5** [comment]
@astean1001 #14 에서 논의 중입니다!
현재 적용 애니메이션 뭘로 할지 검토 중인 상황입니다.

감사합니다.

**Comment by Ryuhwangbyeol** [comment]
14에서 일괄적으로 진행하고, #28 본 이슈는 클로즈하겠습니다.
