### ISSUE TITLE
프로필 텍스트 정렬 문제

### ISSUE THREAD

**Issue by KarryLenka** [SCV-Soft/SCV-Soft.github.io#30]
<img width="616" alt="2018-10-15 1 43 23" src="https://user-images.githubusercontent.com/20009097/46930587-71003e00-d081-11e8-9422-df7cb546d8f3.png">
<img width="459" alt="2018-10-15 1 43 28" src="https://user-images.githubusercontent.com/20009097/46930588-7198d480-d081-11e8-95e2-e3ff8cebccf3.png">

텍스트 좌우정렬 -> 좌측정렬로 변경 부탁드립니다.

*테스트 환경
MacBook Pro (Retina, 13-inch, Early 2015 , MacOS 10.14) (Firefox 62.0.2 / Chrome 69.0.3497.100 / Safari 12.0)

**Comment by benjioh5** [comment]
바꿨습니다

**Comment by KarryLenka** [comment]
변경된 것 확인했습니다. 이슈 클로징 하겠습니다.
