### ISSUE TITLE
질문사항 : 이전에 MOU 진행한곳은 어떻게 되나요?

### ISSUE THREAD

**Issue by Ryuhwangbyeol** [SCV-Soft/SCV-Soft.github.io#49]
이전에 MOU진행했던 업체(KDEX 등) 사이트에 올려야 할까요?
MOU업체 중 멀리 길건너 친구들이 가져가야하는 회사랑 구분하는것도 필요할듯 하네요

**Comment by benjioh5** [comment]
@Ryuhwangbyeol 일단 MOU는 해지 안 하는 이상은 법적 효력이 계속 남아서, 그냥 냅둬도 된다고 생각합니다만. 일단, 각각 MOU 맺은 회사랑 연락을 해서 해지 수순을 밟아야하지 않을까 싶습니다
