### ISSUE TITLE
[PC,태블릿,모바일 공통] 하단 footer 수정사항

### ISSUE THREAD

**Issue by Ryuhwangbyeol** [SCV-Soft/SCV-Soft.github.io#9]
![0813-3 007](https://user-images.githubusercontent.com/13708611/46350840-c0616a00-c690-11e8-8bf0-1aa28ed5325d.jpeg)

[*] 로고와 글씨간의 위 아래 간격 늘리기
[*] 사이트맵, 회사 주소 영역 높이 맞추기
[*] 빨간 글씨 아래 내용 간격 맞추기

**Comment by Ryuhwangbyeol** [comment]
배경색 빼 주세요! 지금은 애매하게 회색이 배경에 깔려있어요

**Comment by benjioh5** [comment]
네네넵 ㅠㅠ

**Comment by benjioh5** [comment]
색 업데이트 완료 @KarryLenka

**Comment by KarryLenka** [comment]
해당 이슈 해결된 것 확인했습니다. 이슈 클로즈 하겠습니다.
